ALTER TABLE intents DROP COLUMN IF EXISTS class;
ALTER TABLE intents DROP COLUMN IF EXISTS type;
ALTER TABLE intents DROP COLUMN IF EXISTS content;
ALTER TABLE intents DROP COLUMN IF EXISTS metadata;
