#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

if ! command -v gomarkdoc >/dev/null 2>&1; then
  echo "gomarkdoc not found in PATH" >&2
  exit 1
fi

mkdir -p docs/api

gomarkdoc -o docs/API.md ./cmd/yanzi ./internal/...
gomarkdoc -o docs/api/cmd.md ./cmd/yanzi
gomarkdoc -o docs/api/internal.md ./internal/...

cat > docs/api/index.md <<'EOF'
# API Documentation

This directory is generated by `./scripts/generate_api_docs.sh`.

- `cmd.md`: exported API for `./cmd/yanzi`
- `internal.md`: exported API for `./internal/...`
- `../API.md`: combined API reference
EOF
